### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by masneyb** [andreiva/raspberry-pi-bme280#1]
I'd like to include your driver in one of my projects (https://github.com/masneyb/pi-yadl), however you did not include what license this code is distributed under. The Adafruit code (https://github.com/adafruit/Adafruit_BME280_Library/blob/master/Adafruit_BME280.cpp) is licensed under the BSD license.

Thanks,

Brian

**Comment by andreiva** [comment]
I added the BSD License text, go ahead and use the code.
I published the code as soon as I got it working and I didn't write proper power management. Now BME280 is initialized, data is read and then code terminates without putting BE280 to standby mode. If you ever write that, please share.

Andrei

**Comment by masneyb** [comment]
Thanks! I'll submit a pull request if I add the power management code.

Thanks,
Brian

**Comment by masneyb** [comment]
I think that you should also include Adafruit's copyright notice from the top of this file: https://github.com/adafruit/Adafruit_BME280_Library/blob/master/Adafruit_BME280.cpp.

**Comment by andreiva** [comment]
I included whole copyright text (i'm not sure what is a proper way to do it, at least Adafruit is now mentioned). The compensation functions that I borrowed from Adafruit, can be found in bme280 datasheet as well.
And thanks for your improvements Brian!

**Comment by masneyb** [comment]
Thanks!
