### ISSUE TITLE
getting what looks like zero values

### ISSUE THREAD

**Issue by gherlein** [andreiva/raspberry-pi-bme280#5]
gherlein@raspberrypi:~/src/raspberry-pi-bme280 $ sudo ./bme280
{"sensor":"bme280", "humidity":0.00, "pressure":0.02, "temperature":0.00, "altitude":38962.29, "timestamp":1600990420}

The breakout board sat in a drawer for a bit, so I'm not even sure the part works... it detects on the bus at 0x77 so it SEEMS to be alive... but getting zeroes is odd.

Anyone seen this before I start digging into the details?

**Comment by LukasSonnabend** [comment]
Hey Greg, did you get this resolved by any chance?

**Comment by andreiva** [comment]
Could you try to verify that your bme280 works, with an Arduino or with a [Python script](https://pypi.org/project/RPi.bme280/)? This seems too weird. 
For the record, I've been running my bme280 on Rpi in the attic, year round, for 5 years now, and it's still working.

**Comment by gherlein** [comment]
That project is now in my dust bin and I don't even have Raspberry. Pi anymore to test with so I can't do anything more on this.
